version: "3.8"
services:
  db:
    platform: linux/amd64
    container_name: mysql_db
    image: mysql:5.7
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-ppassword"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_api_db
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: app_c
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    tty: true
    depends_on:
      db:
        condition: service_healthy

  ngrok:
    container_name: ngrok
    platform: linux/amd64
    image: wernight/ngrok:latest
    ports:
      - ${NGROK_PORT:-4040}:4040
    environment:
      NGROK_PORT: app:8080

volumes:
  data-volume:
